#ifndef BONJOUR_HPP
#define BONJOUR_HPP
#include <string>
#include <list>
#include <vector>

class Bonjour
{
    std::string m_msg;
    int m_int;
    //std::vector<int> m_vector; // BAD IDEA
public:
    // Constructor
    Bonjour(std::string msg = "", int x = 7);
    // Methods
    void greet();
    int sum(int x, int y);
    // Properties
    // - int
    void set_int(int x);
    int get_int() const;
    // - std::string
    void set_msg(std::string msg);
    std::string get_msg() const;
    // - std::vector:
    //void set_vector(std::vector<int> v); // The property generated by Py++ is unusable.
    //std::vector<int> get_vector() const; // The property generated by Py++ is unusable.
    std::vector<int> vector; // Py++ only generates RO access
    std::list<int> list;     // Not supported by Py++
};

#endif
